auto: true
server: true
theme: jekyll-theme-cayman
markdown: kramdown
server_port: 3000
pygments: false
lsi: false
permalink: /:year/:month/:day/:title.html
#paginate: 10
name: byKG  
description: Kevin Gailey Portfolio
url: https://by.kevingailey.com
rss: https://kevingailey.com/feed.xml
logo: https://kevingailey.com/img/C3.jpg
