auto: true
server: true
markdown: kramdown
server_port: 3000
pygments: false
lsi: false
permalink: /:year/:month/:day/:title.html
#paginate: 10
markdown: rdiscount
name: PlexPortal  
description: Plex Portal by KG
url: http://kevingailey.com
rss: http://kevingailey.com/feed.xml
logo: http://kevingailey.com/img/W5-lights.png